package com;
/*
 * This Java source file was generated by the Gradle 'init' task.
 * 1. Modificare din primary
 * 2. Modificare din primary
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
